"""added reservation table

Revision ID: 46194693de78
Revises: 70eddf7c6799
Create Date: 2023-04-10 21:21:17.784405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46194693de78'
down_revision = '70eddf7c6799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('occasion', sa.String(length=30), nullable=False))
        batch_op.drop_column('table_id')
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('occasion')
        batch_op.drop_column('guests')

    op.create_table('table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=False),
    sa.Column('availability', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
