"""edited time column

Revision ID: c795e88da42d
Revises: c9e06a3efc00
Create Date: 2023-04-10 21:28:56.043748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c795e88da42d'
down_revision = 'c9e06a3efc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=30),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
