"""edited date column

Revision ID: c9e06a3efc00
Revises: 46194693de78
Create Date: 2023-04-10 21:28:06.711062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e06a3efc00'
down_revision = '46194693de78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=30),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
